//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlySkyServices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightDBEntities : DbContext
    {
        public FlightDBEntities()
            : base("name=FlightDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_AirportMasters> M_AirportMasters { get; set; }
        public virtual DbSet<M_AviationCompanyMaster> M_AviationCompanyMaster { get; set; }
        public virtual DbSet<M_CityMaster> M_CityMaster { get; set; }
        public virtual DbSet<M_FlightInfo> M_FlightInfo { get; set; }
        public virtual DbSet<M_MasterTable> M_MasterTable { get; set; }
        public virtual DbSet<M_StateCountryMaster> M_StateCountryMaster { get; set; }
        public virtual DbSet<T_FlightsTable> T_FlightsTable { get; set; }
    }
}
