//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlySkyServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_AirportMasters
    {
        public int AirportID { get; set; }
        public string AirportCode { get; set; }
        public string AirportName { get; set; }
        public int TerminalCount { get; set; }
        public int CityID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual M_CityMaster M_CityMaster { get; set; }
    }
}
