//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlySkyServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CityMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_CityMaster()
        {
            this.M_AirportMasters = new HashSet<M_AirportMasters>();
            this.M_AviationCompanyMaster = new HashSet<M_AviationCompanyMaster>();
            this.T_FlightsTable = new HashSet<T_FlightsTable>();
            this.T_FlightsTable1 = new HashSet<T_FlightsTable>();
        }
    
        public int CityID { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public int StateCountryID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_AirportMasters> M_AirportMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_AviationCompanyMaster> M_AviationCompanyMaster { get; set; }
        public virtual M_StateCountryMaster M_StateCountryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FlightsTable> T_FlightsTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FlightsTable> T_FlightsTable1 { get; set; }
    }
}
