//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlySkyServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FlightsTable
    {
        public int FlightTableID { get; set; }
        public int FlightId { get; set; }
        public string FlightNumber { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public int Departure { get; set; }
        public int Arrival { get; set; }
        public int FlightStatus { get; set; }
        public int DelayStatus { get; set; }
        public string DelayedReason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
    
        public virtual M_CityMaster M_CityMaster { get; set; }
        public virtual M_CityMaster M_CityMaster1 { get; set; }
        public virtual M_FlightInfo M_FlightInfo { get; set; }
        public virtual M_MasterTable M_MasterTable { get; set; }
        public virtual M_MasterTable M_MasterTable1 { get; set; }
    }
}
